name: CI
on:
- push
- pull_request
jobs:
  main:
    strategy:
      matrix:
        os:
        - ubuntu-18.04
        - ubuntu-20.04
        - ubuntu-22.04
        cc:
        - gcc
        - clang
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2
    - name: check C compiler version
      run:
        ${{matrix.cc}} --version
    - name: build
      run:
        make CC=${{matrix.cc}}
    - name: set up APT
      if: matrix.cc == 'gcc'
      run: |
        printf 'Apt::Install-Recommends "false";\n' | sudo tee -a /etc/apt/apt.conf
        sudo apt-get update
    - name: run cppcheck
      if: matrix.cc == 'gcc'
      run: |
        sudo apt-get install cppcheck
        cppcheck --error-exitcode=1 *.c
    - name: check README syntax
      if: startsWith(matrix.os, 'ubuntu-2')
      run: |
        python3 -m pip install restructuredtext-lint pygments
        rst-lint --level=info --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
